### ISSUE TITLE
Build error on linux-6.9

### ISSUE THREAD

**Issue by mmoya** [mmoya/asix-usb-nic-linux-driver#2]
Fails to build on 6.9.1:

```
ax88179a_772d.c:301:27: error: initialization of ‘int (*)(struct net_device *, struct ethtool_keee *)’ from incompatible pointer type ‘int (*)(struct net_device *, struct ethtool_eee *)’ [-Wincompatible-pointer-types]
```

**Comment by mmoya** [comment]
Commit 22b67c2 fixes the issue.

**Comment by mmoya** [comment]
Branch [linux-6.9](/mmoya/asix-usb-nic-linux-driver/tree/linux-6.9) rebased on top of 3.2.0.

**Comment by mmoya** [comment]
Upstream fixed this.
